# Generated by Django 3.1.6 on 2021-04-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_cheatsheet_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatsheet',
            name='category',
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='basic_app.category'),
        ),
    ]
